// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Sidebar } from "@/components/sidebar";
import Navbar from "@/components/navbar";
import Login from "./login/page";
import { logado } from "./page";

/**
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ cn("min-h-screen bg-background font-sans antialiased"  )}
      >
        
        { logado ? (
          <>
          <Sidebar/>
           <Navbar/>
           {children}

           </>
           ) : (
              <Login/>
          )
      }

      </body>
    </html>
  );
}
